services:
  hello-server-1:
    image: hello-server:latest
    container_name: hello-server-1
    networks:
      - proxy-network
    restart: unless-stopped

  hello-server-2:
    image: hello-server:latest
    container_name: hello-server-2
    networks:
      - proxy-network
    restart: unless-stopped

  hello-server-3:
    image: hello-server:latest
    container_name: hello-server-3
    networks:
      - proxy-network
    restart: unless-stopped
  proxy-server:
    image: proxy-server:latest
    container_name: proxy-server
    networks:
      - proxy-network
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
networks:
  proxy-network:
    driver: bridge